services:
  db:
    image: mysql:8.0
    container_name: mysql-cs251
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cs251db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend-cs251-container
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: cs251db
      DB_USER: root
      DB_PASSWORD: 1234

volumes:
  mysql_data: