from pydantic import BaseModel, ConfigDict, Field
from datetime import date, time, datetime
from typing import Optional
from decimal import Decimal

# i base these schemas's field names from DATA Dictionary. if oopsie daisy happens, then i cant read.
# "model_config = ConfigDict(from_attributes=True)" allows Pydantic to communicate with sqlalchemy. This is true for all the schemas in this file, so I don't repeat this explanation for each schema.

# Branch Shemas
class BranchBase(BaseModel):
    # contains all necessary fields except BID, which is auto-generated by the database.
    BName: str
    BLocation: str
    BPhoneNumber: str

class BranchCreate(BranchBase):
    pass

class BranchResponse(BranchBase):
    BID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Branch Schemas

# Theater Schemas
class TheaterBase(BaseModel):
    # contains all necessary fields except ThID, which is auto-generated by the database.
    ThNumber: int
    ThType: str
    Capacity: int
    BID: int

class TheaterCreate(TheaterBase):
    pass

class TheaterResponse(TheaterBase):
    ThID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Theater Schemas

#  Movie Schemas
class MovieBase(BaseModel):
    # contains all necessary fields except MID, which is auto-generated by the database.
    MName: str
    Genre: str
    Duration: int
    AgeRating: str
    Description: Optional[str] = None
    ReleaseDate: date
    Actor: Optional[str] = None
    Director: Optional[str] = None
    ScoreRating: Optional[Decimal] = Field(default=0.0, max_digits=3, decimal_places=1)
    AID: int

class MovieCreate(MovieBase):
    pass

class MovieUpdate(BaseModel):
    MName: Optional[str] = None
    Genre: Optional[str] = None
    Duration: Optional[int] = None
    AgeRating: Optional[str] = None
    Description: Optional[str] = None
    ReleaseDate: Optional[date] = None
    Actor: Optional[str] = None
    Director: Optional[str] = None
    ScoreRating: Optional[Decimal] = None

class MovieResponse(MovieBase):
    MID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Movie Schemas

# Showtime Schemas
class ShowtimeBase(BaseModel):
    # contains all necessary fields except ShowtimeID, which is auto-generated by the database.
    ShowDate: date
    StartTime: time
    EndTime: time
    ThID: int
    MID: int

class ShowtimeCreate(ShowtimeBase):
    pass

class ShowtimeResponse(ShowtimeBase):
    ShowtimeID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Showtime Schemas

# Seat Schemas
class SeatBase(BaseModel):
    # contains all necessary fields except SeatID, which is auto-generated by the database.
    SeatStatus: str
    SeatRow: str
    SeatNumber: int
    SeatType: str
    ThID: int

class SeatCreate(SeatBase):
    pass

class SeatResponse(SeatBase):
    SeatID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Seat Schemas

# Booking Schemas
class BookingBase(BaseModel):
    # contains all necessary fields except BookingID, which is auto-generated by the database.
    BookingDate: date
    BookingStatus: str
    TotalPrice: Decimal
    UID: int
    ShowtimeID: int
    PromotionID: Optional[int] = None

class BookingCreate(BookingBase):
    pass

class BookingResponse(BookingBase):
    BookingID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Booking Schemas

# Ticket Schemas
class TicketBase(BaseModel):
    # contains all necessary fields except TicketID, which is auto-generated by the database.
    SeatID: int
    BookingID: int
    Price: Decimal

class TicketCreate(TicketBase):
    pass

class TicketResponse(TicketBase):
    TicketID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Ticket Schemas

# Payment Schemas
class PaymentBase(BaseModel):
    # contains all necessary fields except PaymentID, which is auto-generated by the database.
    Amount: Decimal
    PaymentStatus: str
    PaymentDate: datetime
    PaymentMethod: str
    BookingID: int

class PaymentCreate(PaymentBase):
    pass

class PaymentResponse(PaymentBase):
    PaymentID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Payment Schemas

# Review Schemas
class ReviewBase(BaseModel):
    ReviewScore: int
    Comment: Optional[str] = None
    UID: int
    MID: int

class ReviewCreate(ReviewBase):
    pass

class ReviewResponse(ReviewBase):
    ReviewID: int
    ReviewDate: date
    model_config = ConfigDict(from_attributes=True)
# \end of Review Schemas