from pydantic import BaseModel, ConfigDict, Field
from datetime import date, time
from typing import Optional
from decimal import Decimal

# i base these schemas's field names from DATA Dictionary. if oopsie daisy happens, then i cant read.
# "model_config = ConfigDict(from_attributes=True)" allows Pydantic to communicate with sqlalchemy. This is true for all the schemas in this file, so I don't repeat this explanation for each schema.

# Branch Shemas
class BranchBase(BaseModel):
    # contains all necessary fields except BID, which is auto-generated by the database.
    BName: str
    BLocation: str
    BPhoneNumber: str

class BranchCreate(BranchBase):
    pass

class BranchResponse(BranchBase):
    BID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Branch Schemas

# Theater Schemas
class TheaterBase(BaseModel):
    # contains all necessary fields except ThID, which is auto-generated by the database.
    ThNumber: int
    ThType: str
    Capacity: int
    BID: int

class TheaterCreate(TheaterBase):
    pass

class TheaterResponse(TheaterBase):
    ThID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Theater Schemas

#  Movie Schemas
class MovieBase(BaseModel):
    # contains all necessary fields except MID, which is auto-generated by the database.
    MName: str
    Genre: str
    Duration: int
    AgeRating: str
    Description: Optional[str] = None
    ReleaseDate: date
    Actor: Optional[str] = None
    Director: Optional[str] = None
    ScoreRating: Optional[Decimal] = Field(default=0.0, max_digits=3, decimal_places=1)
    AID: int

class MovieCreate(MovieBase):
    pass

class MovieUpdate(BaseModel):
    MName: Optional[str] = None
    Genre: Optional[str] = None
    Duration: Optional[int] = None
    AgeRating: Optional[str] = None
    Description: Optional[str] = None
    ReleaseDate: Optional[date] = None
    Actor: Optional[str] = None
    Director: Optional[str] = None
    ScoreRating: Optional[Decimal] = None

class MovieResponse(MovieBase):
    MID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Movie Schemas

# Showtime Schemas
class ShowtimeBase(BaseModel):
    # contains all necessary fields except ShowtimeID, which is auto-generated by the database.
    ShowDate: date
    StartTime: time
    EndTime: time
    ThID: int
    MID: int

class ShowtimeCreate(ShowtimeBase):
    pass

class ShowtimeResponse(ShowtimeBase):
    ShowtimeID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Showtime Schemas

# Seat Schemas
class SeatBase(BaseModel):
    # contains all necessary fields except SeatID, which is auto-generated by the database.
    SeatStatus: str
    SeatRow: str
    SeatNumber: int
    SeatType: str
    ThID: int

class SeatCreate(SeatBase):
    pass

class SeatResponse(SeatBase):
    SeatID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Seat Schemas