from pydantic import BaseModel, ConfigDict
from typing import Optional
from datetime import date
from decimal import Decimal

# Booking Schemas
class BookingBase(BaseModel):
    # contains all necessary fields except BookingID, which is auto-generated by the database.
    BookingDate: date
    BookingStatus: str
    TotalPrice: Decimal
    UID: int
    ShowtimeID: int
    PromotionID: Optional[int] = None

class BookingCreate(BookingBase):
    pass

class BookingResponse(BookingBase):
    BookingID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Booking Schemas