# Branch Shemas
from pydantic import BaseModel, ConfigDict

class BranchBase(BaseModel):
    # contains all necessary fields except BID, which is auto-generated by the database.
    BName: str
    BLocation: str
    BPhoneNumber: str

class BranchCreate(BranchBase):
    pass

class BranchResponse(BranchBase):
    BID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Branch Schemas