from pydantic import BaseModel, ConfigDict, Field
from typing import Optional
from datetime import date
from decimal import Decimal
#  Movie Schemas
class MovieBase(BaseModel):
    # contains all necessary fields except MID, which is auto-generated by the database.
    MName: str
    Genre: str
    Duration: int
    AgeRating: str
    Description: Optional[str] = None
    ReleaseDate: date
    Actor: Optional[str] = None
    Director: Optional[str] = None
    ScoreRating: Optional[Decimal] = Field(default=0.0, max_digits=3, decimal_places=1)
    AID: int

class MovieCreate(MovieBase):
    pass

class MovieUpdate(BaseModel):
    MName: Optional[str] = None
    Genre: Optional[str] = None
    Duration: Optional[int] = None
    AgeRating: Optional[str] = None
    Description: Optional[str] = None
    ReleaseDate: Optional[date] = None
    Actor: Optional[str] = None
    Director: Optional[str] = None
    ScoreRating: Optional[Decimal] = None

class MovieResponse(MovieBase):
    MID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Movie Schemas