from pydantic import BaseModel, ConfigDict
from datetime import date
from decimal import Decimal
# Payment Schemas
class PaymentBase(BaseModel):
    # contains all necessary fields except PaymentID, which is auto-generated by the database.
    Amount: Decimal
    PaymentStatus: str
    PaymentDate: date
    PaymentMethod: str
    BookingID: int

class PaymentCreate(PaymentBase):
    pass

class PaymentResponse(PaymentBase):
    PaymentID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Payment Schemas
