from pydantic import BaseModel, ConfigDict
from typing import Optional
from decimal import Decimal
from datetime import date

#promotion schema
class PromotionBase(BaseModel):
     # contains all necessary fields except PromotionID, which is auto-generated by the database.
    PromotionName: str
    DiscountType: Optional[str] = None # Percentage, Fixed Amount
    DiscountValue: Decimal
    StartDate: date
    EndDate: date
    AID: int

class PromotionCreate(PromotionBase):
    pass

class PromotionUpdate(BaseModel):
    PromotionName: Optional[str] = None
    DiscountType: Optional[str] = None
    DiscountValue: Optional[Decimal] = None
    StartDate: Optional[date] = None
    EndDate: Optional[date] = None

class PromotionResponse(PromotionBase):
    PromotionID: int
    model_config = ConfigDict(from_attributes=True)
# /end of promotion schema