from pydantic import BaseModel, ConfigDict
from decimal import Decimal
from typing import Optional

# Seat Schemas
class SeatBase(BaseModel):
    # contains all necessary fields except SeatID, which is auto-generated by the database.
    SeatStatus: str
    SeatRow: str
    SeatNumber: int
    SeatType: str
    ThID: int

class SeatCreate(SeatBase):
    pass

class SeatResponse(SeatBase):
    SeatID: int
    Price: Optional[Decimal] = None
    model_config = ConfigDict(from_attributes=True)
# \end of Seat Schemas
