from pydantic import BaseModel, ConfigDict, Field, model_validator
from datetime import date, time
from typing import List, Optional
from decimal import Decimal

# Showtime Schemas
class ShowtimeBase(BaseModel):
    # contains all necessary fields except ShowtimeID, which is auto-generated by the database.
    ShowDate: date
    StartTime: time
    EndTime: time
    ThID: int
    MID: int

class ShowtimeCreate(ShowtimeBase):
    EndTime: Optional[time] = None
    Price: Optional[Decimal] = Field(default=None, gt=0)
    PremiumExtraPrice: Optional[Decimal] = Field(default=None, ge=0)


class AdminShowtimeCreate(BaseModel):
    MID: Optional[int] = None
    MovieKeyword: Optional[str] = None
    ThID: Optional[int] = None
    Branch: Optional[str] = None
    Theater: Optional[str] = None
    ShowDate: date
    StartTime: time
    EndTime: Optional[time] = None
    Price: Optional[Decimal] = Field(default=None, gt=0)
    PremiumExtraPrice: Optional[Decimal] = Field(default=None, ge=0)

    @model_validator(mode="after")
    def validate_identity_fields(self):
        if self.MID is None and not (self.MovieKeyword and self.MovieKeyword.strip()):
            raise ValueError("MID or MovieKeyword is required")

        if self.ThID is None:
            if not (self.Branch and self.Branch.strip()):
                raise ValueError("Branch is required when ThID is not provided")
            if not (self.Theater and self.Theater.strip()):
                raise ValueError("Theater is required when ThID is not provided")

        return self

class ShowtimeResponse(ShowtimeBase):
    ShowtimeID: int
    model_config = ConfigDict(from_attributes=True)

class ShowtimeSlotResponse(BaseModel):
    ShowtimeID: int
    StartTime: str
    EndTime: str
    Language: str

class TheaterShowtimeGroupResponse(BaseModel):
    ThID: int
    ThName: str
    Format: Optional[str] = None
    Showtimes: List[ShowtimeSlotResponse]

class BranchShowtimeGroupResponse(BaseModel):
    BID: int
    BName: str
    BLocation: str
    Theaters: List[TheaterShowtimeGroupResponse]

class MovieShowtimeDateGroupResponse(BaseModel):
    ShowDate: date
    Branches: List[BranchShowtimeGroupResponse]
# \end of Showtime Schemas
