from pydantic import BaseModel, ConfigDict, Field
from datetime import date, time
from typing import List, Optional

# Showtime Schemas
class ShowtimeBase(BaseModel):
    # contains all necessary fields except ShowtimeID, which is auto-generated by the database.
    ShowDate: date
    StartTime: time
    EndTime: time
    ThID: int
    MID: int

class ShowtimeCreate(ShowtimeBase):
    pass

class ShowtimeResponse(ShowtimeBase):
    ShowtimeID: int
    model_config = ConfigDict(from_attributes=True)

class ShowtimeSlotResponse(BaseModel):
    ShowtimeID: int
    StartTime: str
    EndTime: str
    Language: str

class TheaterShowtimeGroupResponse(BaseModel):
    ThID: int
    ThName: str
    Format: Optional[str] = None
    Showtimes: List[ShowtimeSlotResponse]

class BranchShowtimeGroupResponse(BaseModel):
    BID: int
    BName: str
    BLocation: str
    Theaters: List[TheaterShowtimeGroupResponse]

class MovieShowtimeDateGroupResponse(BaseModel):
    ShowDate: date
    Branches: List[BranchShowtimeGroupResponse]
# \end of Showtime Schemas
