from pydantic import BaseModel, ConfigDict, Field
from datetime import date, time

# Showtime Schemas
class ShowtimeBase(BaseModel):
    # contains all necessary fields except ShowtimeID, which is auto-generated by the database.
    ShowDate: date
    StartTime: time
    EndTime: time
    ThID: int
    MID: int

class ShowtimeCreate(ShowtimeBase):
    pass

class ShowtimeResponse(ShowtimeBase):
    ShowtimeID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Showtime Schemas