from pydantic import BaseModel, ConfigDict

# Theater Schemas
class TheaterBase(BaseModel):
    # contains all necessary fields except ThID, which is auto-generated by the database.
    ThNumber: int
    ThType: str
    Capacity: int
    BID: int

class TheaterCreate(TheaterBase):
    pass

class TheaterResponse(TheaterBase):
    ThID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Theater Schemas