from pydantic import BaseModel, ConfigDict
from decimal import Decimal

# Ticket Schemas
class TicketBase(BaseModel):
    # contains all necessary fields except TicketID, which is auto-generated by the database.
    SeatID: int
    BookingID: int
    Price: Decimal

class TicketCreate(TicketBase):
    pass

class TicketResponse(TicketBase):
    TicketID: int
    model_config = ConfigDict(from_attributes=True)
# \end of Ticket Schemas